baseURL: https://janw.xyz/
languageCode: en-us
title: Janw.xyz
description:
theme: janwxyz
paginate: 5

params:
  author: Jan Willhaus
  description: Jack of all trades and a master of some
  repository: https://github.com/janwh/janwh.github.io
  isso_comments_base: https://janw.xyz/comments
taxonomies:
  tag: ~
  group: ~
  category: ~
