baseURL: https://janw.xyz/
languageCode: en-us
title: Janw.xyz
description:
theme: janwxyz
assetDir: themes/janwxyz/src
paginate: 5

# Required for encoded HTML in imprint
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  author: Jan Willhaus
  description: >-
    Jan Willhaus – Jack of all trades, master of some. Internet Aficionado,
    tinkerer, audio engineer gone software engineering. This is my
    website where I keep a few things about me, and some articles posted in
    my blog. Thanks for stopping by.
  greeting: Hi there!
  welcome: "My name is Jan,<br> I do things on the internet."

  isso_comments_base: /comments

disableKinds:
- taxonomy
- term
- tags

menu:
  main:
    - identifier: about
      name: About Me
      url: /about/
      pre: duotone/user-astronaut
      weight: -200
    - identifier: contact
      name: Contact
      url: /contact/
      pre: duotone/handshake
      weight: -150
    - identifier: blog
      name: Blog
      weight: 100
      url: /blog/
      pre: duotone/pencil-alt

  sidebarAddedMain:
    - identifier: feed
      name: Subscribe
      title: RSS-Feed
      url: /feed.xml
      weight: 100
      pre: duotone/rss


  profiles:
    - name: GitHub
      url: https://github.com/janw
      pre: brands/github-square
      weight: -400
    - name: Flickr
      title: Flickr.com
      url: https://www.flickr.com/photos/janwillhaus/
      pre: brands/flickr
      weight: 550
    - name: LinkedIn
      url: https://www.linkedin.com/in/janw/
      pre: brands/linkedin
      weight: 500
    - name: Twitter
      url: https://twitter.com/janw_xyz
      pre: brands/twitter-square
      weight: 600

outputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "feed"
